import { PayListWrap, ListTit, ListPrice } from './PayList.style';

const PayList = () => {
  return (
    <PayListWrap>
      <li>
        <ListTit>
          <p>정읍옌락김밥</p>
          <span>18,000원</span>
        </ListTit>
        <ListPrice>앱스토어</ListPrice>
      </li>
      <li>
        <ListTit>
          <p>정읍옌락김밥</p>
          <span>18,000원</span>
        </ListTit>
        <ListPrice>앱스토어</ListPrice>
      </li>
      <li>
        <ListTit>
          <p>정읍옌락김밥</p>
          <span>18,000원</span>
        </ListTit>
        <ListPrice>앱스토어</ListPrice>
      </li>
      <li>
        <ListTit>
          <p>정읍옌락김밥</p>
          <span>18,000원</span>
        </ListTit>
        <ListPrice>앱스토어</ListPrice>
      </li>
      <li>
        <ListTit>
          <p>정읍옌락김밥</p>
          <span>18,000원</span>
        </ListTit>
        <ListPrice>앱스토어</ListPrice>
      </li>
      <li>
        <ListTit>
          <p>정읍옌락김밥</p>
          <span>18,000원</span>
        </ListTit>
        <ListPrice>앱스토어</ListPrice>
      </li>{' '}
      <li>
        <ListTit>
          <p>정읍옌락김밥</p>
          <span>18,000원</span>
        </ListTit>
        <ListPrice>앱스토어</ListPrice>
      </li>
      <li>
        <ListTit>
          <p>정읍옌락김밥</p>
          <span>18,000원</span>
        </ListTit>
        <ListPrice>앱스토어</ListPrice>
      </li>
      <li>
        <ListTit>
          <p>정읍옌락김밥</p>
          <span>18,000원</span>
        </ListTit>
        <ListPrice>앱스토어</ListPrice>
      </li>{' '}
      <li>
        <ListTit>
          <p>정읍옌락김밥</p>
          <span>18,000원</span>
        </ListTit>
        <ListPrice>앱스토어</ListPrice>
      </li>
      <li>
        <ListTit>
          <p>정읍옌락김밥</p>
          <span>18,000원</span>
        </ListTit>
        <ListPrice>앱스토어</ListPrice>
      </li>
      <li>
        <ListTit>
          <p>정읍옌락김밥</p>
          <span>18,000원</span>
        </ListTit>
        <ListPrice>앱스토어</ListPrice>
      </li>{' '}
      <li>
        <ListTit>
          <p>정읍옌락김밥</p>
          <span>18,000원</span>
        </ListTit>
        <ListPrice>앱스토어</ListPrice>
      </li>
      <li>
        <ListTit>
          <p>정읍옌락김밥</p>
          <span>18,000원</span>
        </ListTit>
        <ListPrice>앱스토어</ListPrice>
      </li>
      <li>
        <ListTit>
          <p>정읍옌락김밥</p>
          <span>18,000원</span>
        </ListTit>
        <ListPrice>앱스토어</ListPrice>
      </li>{' '}
      <li>
        <ListTit>
          <p>정읍옌락김밥</p>
          <span>18,000원</span>
        </ListTit>
        <ListPrice>앱스토어</ListPrice>
      </li>
      <li>
        <ListTit>
          <p>정읍옌락김밥</p>
          <span>18,000원</span>
        </ListTit>
        <ListPrice>앱스토어</ListPrice>
      </li>
      <li>
        <ListTit>
          <p>정읍옌락김밥</p>
          <span>18,000원</span>
        </ListTit>
        <ListPrice>앱스토어</ListPrice>
      </li>
    </PayListWrap>
  );
};

export default PayList;
